// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbzU1I3Dt8l6vOQ0aOFCyT9jVZAOYyitg',
    appId: '1:709220974773:web:0dacb582a2417f9cbb3efc',
    messagingSenderId: '709220974773',
    projectId: 'dailydiary-b780a',
    authDomain: 'dailydiary-b780a.firebaseapp.com',
    storageBucket: 'dailydiary-b780a.appspot.com',
    measurementId: 'G-1F9VYG0BYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdg3rYmrug2KhditJsxbD3B4q9uu4ozpw',
    appId: '1:709220974773:android:9e012630b2b80bbdbb3efc',
    messagingSenderId: '709220974773',
    projectId: 'dailydiary-b780a',
    storageBucket: 'dailydiary-b780a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnXSHUkvBhgGmUfgIW87Z6aS6IWby8deI',
    appId: '1:709220974773:ios:782344c4c009beccbb3efc',
    messagingSenderId: '709220974773',
    projectId: 'dailydiary-b780a',
    storageBucket: 'dailydiary-b780a.appspot.com',
    iosBundleId: 'com.dailydiary.dailydiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnXSHUkvBhgGmUfgIW87Z6aS6IWby8deI',
    appId: '1:709220974773:ios:b9dce9021c2cf92bbb3efc',
    messagingSenderId: '709220974773',
    projectId: 'dailydiary-b780a',
    storageBucket: 'dailydiary-b780a.appspot.com',
    iosBundleId: 'com.dailydiary.dailydiary.RunnerTests',
  );
}
